MLeRP is split into two regions which users can choose between - one based in Monash (Melbourne, Victoria) and one based in QCIF (Brisbane, Queensland). The clusters have seperate file systems, so you will have to transfer your files across if you'd like to switch regions.

## Monash

The Monash region is designed to be flexible. Users use CPU notebook or terminal sessions along with a Dask scheduler as an interface to the HPC system. This allows users to change the amount of compute they request are using entirely within the notebook and return valuable resources when they no longer need it. See [this FAQ](/faq.qmd#how-much-compute-should-i-ask-for-with-my-slurmcluster) for advice on requesting resources through the Dask scheduler.

Monash workloads are also able to make use of attached NVME for temporary file storage.

Notebook or terminal sessions in three sizes:  

- Small 
  - 4 VCPUs 
  - 16 GB RAM 
- Medium  
  - 8 VCPUs
  - 32 GB RAM  
- Large  
  - 8 VCPUs
  - 64 GB RAM  

Six nodes with:

- 54 VCPUs
- 460 GB RAM
- 1.5 TB NVME
- 2 A100s, each split with MIG into:
  - 1 20 GB VRAM
  - 2 10 GB VRAM

## QCIF
The QCIF region uses a more traditional approach with A100 GPU enabled notebook or terminal sessions. This user experience is much closer to using a service like Google Colab.

GPU notebook or terminal sessions in three sizes:

- Regular
  - 20 VCPUs
  - 190 GB RAM
  - 10 GB VRAM
- Double
  - 20 VCPUs
  - 190 GB RAM
  - 20 GB VRAM
- Node
  - 60 VCPUs
  - 570 GB RAM
  - 2x 10 GB VRAM + 1x 20 GB VRAM
  