---
title: Getting Started
---

Welcome to MLeRP!

Most users will find that the easiest way to start using MLeRP will be through the [Strudel2 Web Interface](/usage/strudel2.qmd). Here you can find the `Terminal` and `Jupyter Lab` applications we have prepared for you. 

We have provided [some python environments](/usage/environments.qmd) for you so you can get started right away, until you eventually outgrow them and feel like you need more control over your packages. At this point, we can help you to transition to maintaining your own environment with whatever applications and packages you need. 

Your home directory will be set up with a quota based on what you told us you'll need to do your research. You can use this space to maintain your datasets, programs and code base. Let us know if you need more space and we'll see what we can do.

Regardless of what compute you choose, in order to start your research here you will need to be able to import your data and code. If you're working with relatively small files, then the simplest way could be to use the FTP clients built into [Jupyter Lab](/connecting/transferring_files.qmd#jupyter-lab) or [VS Code](/connecting/transferring_files.qmd#vs-code). Otherwise something like [rsync](/connecting/transferring_files.qmd#rsync) may be more appropriate.

If you are maintaining your code base through Git, then you will likely need to set up an ssh key and add it to your account before pulling down your repository. To use the right ssh key when using git you will need to set up an ssh config that will look something like this:

```
Host github.com
        User git
        HostName github.com
        IdentityFile ~/.ssh/github
```

If you are more comfortable using a Git GUI we reccommend [connecting to MLeRP using VS Code](/connecting/vscode.qmd) and using it's [Git extensions](https://code.visualstudio.com/docs/sourcecontrol/overview).

All of our documentation is programmatically generated with [Quarto](https://quarto.org/) and is available on [GitHub](https://github.com/mitchellshargreaves-monash/MLeRP-Documentation). We encourage users to clone a copy and go through our tutorials at their own pace.

```
git clone git@github.com:mitchellshargreaves-monash/MLeRP-Documentation.git
```

If you feel that our documentation does not serve your use case well and could be improved, we welcome contributions through pull requests.